### ISSUE TITLE
Linting Error for display: box property

### ISSUE THREAD

**Issue by ddigioia** [trendmicro-frontend/react-grid-system#3]
Hey great library,

Had one question because my linter is giving me trouble about a display property you set. Is there a reason for including the legacy property `display: box;` here => https://github.com/trendmicro-frontend/react-grid-system/blob/master/dist/react-grid-system.css#L43?

I see you declare `display: flex;` right under it so was wondering if `display: box;` is a fallback incase the browser doesn't support the flex value?

https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by cheton** [comment]
This is a good point. `display: box` is no longer recognized by modern browsers and it's not part of flexbox since 2012. I will remove it in the next patch release.

**Comment by cheton** [comment]
Fixed in [1.1.0](https://github.com/trendmicro-frontend/react-grid-system/releases/tag/v1.1.0)

**Comment by ddigioia** [comment]
Amazing, thank you for the quick response!
